### ISSUE TITLE
Fold functions doesn't work with PHP PSR standard new line braces

### ISSUE THREAD

**Issue by marcusorjames** [robballou/atom-fold-functions#14]
e.g.

```
public function foo( $bar ) 
{
    return $bar;
}
```

will not correctly fold

**Comment by robballou** [comment]
To support this will require re-working on this currently works. Essentially this plugin works off of the scopes within a line and requires that the scope specifies that this is a function. It then folds the line that specifies that it is a function. Unfortunately, files with the format above specify the function scope on the public function line, but not on the subsequent lines.

I haven't looked at this yet, but I wonder if supporting ctags is the better way to go and if that would help this or not. Failing that, we would need to check if the function line is foldable and if not, try to fold the next line. If anyone wants to help out, that would be great. Otherwise I will try to figure out a solution when I get some time to work on this again.
