### ISSUE TITLE
can autofold depend on file？

### ISSUE THREAD

**Issue by SimplyY** [robballou/atom-fold-functions#3]
For example， in js

![image](https://cloud.githubusercontent.com/assets/8455579/10357897/5333ba00-6dba-11e5-97b6-cd4776d32eb4.png)

feel not good

**Comment by robballou** [comment]
There might be a couple ways:
1. The easiest is to not fold short files. This was easy enough that I have implemented it already and published a new version, `0.4.0`. You can configure the number of lines for the cutoff or turn it off in options. The default cutoff is at 42 lines.
2. The more difficult option will be determine how many autofold functions there are in a document before folding and only fold if there is more than one. This will stop the JavaScript example above from folding and likely others like this. I'm not sure of the best way to go about this just yet because it will require looping over the file and then remembering the positions of what to fold, etc. Not impossible so maybe I will look at it if I get time :)

**Comment by SimplyY** [comment]
oh I see 0.4.0.

very good job.
